# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale: "en-US"
site_theme: "default" # Currently available options are "default", "air"
title: "Kolja Reuter"
title_separator: "-"
name: &name "Kolja Reuter"
description: &description "B.Sc. (Astro-) & Physics"
url: https://koljareuter.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "koljareuter.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
author:
  avatar: "profile.png"
  name: "Kolja"
  pronouns: # example: "she/her" (left blank as in original)
  bio: "Extragalactic Astronomy"
  location: "Germany"
  employer: "Ruprecht-Karls University Heidelberg"
  uri: # URL (left blank)
  email: "koljareuter.8@gmail.com"

  # Academic websites
  academia: # URL (left blank)
  arxiv: # URL (left blank)
  googlescholar: # "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep: # URL (left blank)
  impactstory: # URL (left blank)
  orcid: "https://orcid.org/0009-0004-7077-8157"
  semantic: # URL (left blank)
  pubmed: # "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate: # URL (left blank)
  scopus: # URL (left blank)

  # Repositories and software development
  bitbucket: # Username (left blank)
  codepen: # Username (left blank)
  dribbble: # Username (left blank)
  github: "https://github.com/koljareuter"
  kaggle: # Username (left blank)
  stackoverflow: # User number or user number and name (left blank)

  # Social media
  artstation: # Username (left blank)
  bluesky: # "bsky.app" (left blank)
  facebook: # Username (left blank)
  flickr: # Username (left blank)
  foursquare: # Username (left blank)
  goodreads: # Username (left blank)
  google_plus: # Username (left blank)
  keybase: # Username (left blank)
  instagram: "https://www.instagram.com/kolja.reuter" # fixed typo "htttps" -> "https"
  lastfm: # Username (left blank)
  linkedin: # Username (left blank)
  mastodon: # URL (left blank)
  medium: # URL (left blank)
  pinterest: # Username (left blank)
  soundcloud: # Username (left blank)
  steam: # Username (left blank)
  telegram: # URL (left blank)
  tumblr: # Username (left blank)
  twitter: # Username (left blank)
  vine: # Username (left blank)
  weibo: # Username (left blank)
  wikipedia: # Username (left blank)
  xing: # Username (left blank)
  youtube: # Username (left blank)
  zhihu: # Username (left blank)

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser: # filename of teaser fallback teaser image placed in /images/, e.g. "500x300.png"
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:
  discourse:
    server: # e.g. meta.discourse.org
  facebook:
    appid:
    num_posts:
    colorscheme:

staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

atom_feed:
  hide: false
  path:

# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
instagram:
  username: "https://www.instagram.com/kolja.reuter" # fixed from "&htttps..."
facebook:
  username:
  app_id:
  publisher:
og_image:
og_description:
social:
  type: # Person or Organization (defaults to Person)
  name:
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults for pages and collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comments: true  # fixed typo from "comment" to "comments"
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
